/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EligibilityMonthlySummary } from '../../models/eligibility-monthly-summary';

export interface GetMonthlyStats1$Params {
  year: number;
}

export function getMonthlyStats1(http: HttpClient, rootUrl: string, params: GetMonthlyStats1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EligibilityMonthlySummary>>> {
  const rb = new RequestBuilder(rootUrl, getMonthlyStats1.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EligibilityMonthlySummary>>;
    })
  );
}

getMonthlyStats1.PATH = '/auth/eligibilityRecords/monthlyStats';
