/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AlternativeProgram } from '../models/alternative-program';
import { EligibleProgram } from '../models/eligible-program';
export interface AiRecommendation {
  alternativeOptions?: string;
  alternativeProgram?: AlternativeProgram;
  careerPath?: string;
  eligibleProgram?: EligibleProgram;
  futureProspects?: string;
  id?: number;
  improvementTips?: string;
  jobOpportunities?: string;
  programName?: string;
}
