/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AiRecommendation } from '../models/ai-recommendation';
import { UniversityEligibility } from '../models/university-eligibility';
export interface AlternativeProgram {
  admissionProbability?: number;
  aiRecommendation?: AiRecommendation;
  categories?: Array<string>;
  cutoffPoints?: {
[key: string]: string;
};
  explanations?: Array<string>;
  id?: string;
  name?: string;
  percentage?: number;
  universityEligibility?: UniversityEligibility;
}
