/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AlternativeProgramDto {
  cutoffPoints?: {
[key: string]: string;
};
  explanation?: Array<string>;
  percentageEligibility?: number;
  programName?: string;
}
