/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthenticationResponse {
  email?: string;
  firstName?: string;
  fullName?: string;
  lastName?: string;
  token?: string;
}
