/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BiodataResponse {
  address?: string;
  dob?: string;
  email?: string;
  firstName?: string;
  gender?: 'Male' | 'Female';
  id?: number;
  lastName?: string;
  middleName?: string;
  phoneNumber?: string;
  recordId?: string;
  region?: 'ASHANTI' | 'BRONG_AHAFO' | 'CENTRAL' | 'EASTERN' | 'GREATER_ACCRA' | 'NORTHERN' | 'UPPER_EAST' | 'UPPER_WEST' | 'VOLTA' | 'WESTERN';
}
