/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DailyPaymentSummary {
  date?: string;
  totalAmount?: number;
  transactionCount?: number;
}
