/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ResultDetail } from '../models/result-detail';
export interface EligibilityRequest {
  categoryIds: Array<number>;
  checkRecordId?: string;
  resultDetails: Array<ResultDetail>;
  universityType?: string;
}
