/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EligibleProgramDto {
  cutoffPoints?: {
[key: string]: string;
};
  percentageEligibility?: number;
  programName?: string;
}
