/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExamCheckRecord } from '../models/exam-check-record';
import { UniversityEligibility } from '../models/university-eligibility';
export interface EligibilityRecord {
  createdAt?: string;
  examCheckRecord?: ExamCheckRecord;
  id?: string;
  universities?: Array<UniversityEligibility>;
  userId?: string;
}
