/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WaecCandidateEntity } from '../models/waec-candidate-entity';
export interface ExamCheckRecord {
  candidateName?: string;
  checkLimit?: number;
  checkStatus?: string;
  createdAt?: string;
  externalRef?: string;
  id?: string;
  lastUpdated?: string;
  paymentStatus?: 'PAID' | 'FAILED' | 'PENDING';
  userId?: string;
  waecCandidateEntity?: WaecCandidateEntity;
}
