/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Biodata } from '../models/biodata';
import { User } from '../models/user';
import { WaecCandidateEntity } from '../models/waec-candidate-entity';
export interface ExamCheckRecord {
  biodata?: Biodata;
  candidateName?: string;
  checkLimit?: number;
  checkStatus?: string;
  createdAt?: string;
  externalRef?: string;
  id?: string;
  lastUpdated?: string;
  paymentStatus?: 'PAID' | 'FAILED' | 'PENDING';
  user?: User;
  waecCandidateEntity?: WaecCandidateEntity;
}
