/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MonthlyRevenueSummary {
  month?: number;
  totalAmount?: number;
  transactionCount?: number;
}
