/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MoolrePaymentRequest {
  accountnumber?: string;
  amount?: number;
  channel?: number;
  currency?: string;
  externalref?: string;
  otpcode?: string;
  payer?: string;
  reference?: string;
  type?: number;
}
