/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MoolrePaymentResponse {
  code?: string;
  data?: string;
  externalref?: string;
  go?: {
};
  message?: string;
  status?: number;
  userMessage?: string;
}
