/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface PaymentStatuss {
  amount?: number;
  externalRef?: string;
  id?: number;
  payee?: string;
  payer?: string;
  secret?: string;
  thirdPartyRef?: string;
  timestamp?: string;
  transactionId?: number;
  txStatus?: number;
  user?: User;
  value?: number;
}
