/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentData {
  accountnumber?: string;
  amount?: number;
  externalref?: string;
  name?: string;
  payer?: string;
  secret?: string;
  terminalid?: string;
  thirdpartyref?: string;
  transactionid?: string;
  ts?: string;
  txstatus?: number;
  value?: number;
}
