/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSummaryDtOs } from '../models/user-summary-dt-os';
export interface PaymentStatusResponseDto {
  amount?: number;
  customer?: UserSummaryDtOs;
  externalRef?: string;
  id?: number;
  payee?: string;
  payer?: string;
  secret?: string;
  thirdPartyRef?: string;
  timestamp?: string;
  transactionId?: number;
  txStatus?: number;
  value?: number;
}
