/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentData } from '../models/payment-data';
export interface PaymentStatusRequest {
  code?: string;
  data?: PaymentData;
  message?: string;
  status?: number;
}
