/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Program } from '../models/program';
export interface ProgramRequestDto {
  programs?: Array<Program>;
  universityId: number;
}
