/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProgramWithCategoriesDto } from '../models/program-with-categories-dto';
export interface ProgramRequestDto {
  programs?: Array<ProgramWithCategoriesDto>;
  universityId: number;
}
