/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Program {
  cutoffPoints?: {
[key: string]: string;
};
  id?: number;
  name?: string;
}
