/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryIdDto } from '../models/category-id-dto';
export interface ProgramWithCategoriesDto {
  categoryIds?: Array<CategoryIdDto>;
  cutoffPoints?: {
[key: string]: string;
};
  name?: string;
}
