/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RegionStatsDto } from '../models/region-stats-dto';
export interface RegionStatsResponse {
  regions?: Array<RegionStatsDto>;
  totalBiodata?: number;
}
