/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AlternativeProgramDto } from '../models/alternative-program-dto';
import { EligibleProgramDto } from '../models/eligible-program-dto';
export interface UniversityEligibilityDto {
  alternativePrograms?: Array<AlternativeProgramDto>;
  eligiblePrograms?: Array<EligibleProgramDto>;
  location?: string;
  type?: string;
  universityName?: string;
}
