/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AlternativeProgram } from '../models/alternative-program';
import { EligibilityRecord } from '../models/eligibility-record';
import { EligibleProgram } from '../models/eligible-program';
export interface UniversityEligibility {
  alternativePrograms?: Array<AlternativeProgram>;
  eligibilityRecord?: EligibilityRecord;
  eligiblePrograms?: Array<EligibleProgram>;
  id?: string;
  location?: string;
  type?: string;
  universityName?: string;
  userId?: string;
}
