/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Program } from '../models/program';
export interface University {
  id?: number;
  location?: string;
  name?: string;
  programs?: Array<Program>;
  type?: 'PUBLIC' | 'PRIVATE';
}
