/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUniversityDto {
  id: number;
  location: string;
  name: string;
  type: 'PUBLIC' | 'PRIVATE';
}
