/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserSummaryDto {
  fullName?: string;
  id?: number;
  signupDate?: string;
  username?: string;
}
