/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserSummaryDtOs {
  firstname?: string;
  fullName?: string;
  id?: number;
  lastname?: string;
  phoneNummber?: string;
}
