/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WaecResultDetailEntity } from '../models/waec-result-detail-entity';
export interface WaecCandidateEntity {
  cindex?: string;
  cname?: string;
  dob?: string;
  examtype?: string;
  examyear?: string;
  gender?: number;
  id?: number;
  resultDetails?: Array<WaecResultDetailEntity>;
}
