/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WeeklyRevenueSummary {
  totalAmount?: number;
  transactionCount?: number;
  weekNumber?: number;
}
