/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DailyPaymentSummary } from '../../models/daily-payment-summary';

export interface GetDailyPaymentStats$Params {
  year: number;
  month: number;
  statusCode?: number;
}

export function getDailyPaymentStats(http: HttpClient, rootUrl: string, params: GetDailyPaymentStats$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DailyPaymentSummary>>> {
  const rb = new RequestBuilder(rootUrl, getDailyPaymentStats.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
    rb.query('month', params.month, {});
    rb.query('statusCode', params.statusCode, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DailyPaymentSummary>>;
    })
  );
}

getDailyPaymentStats.PATH = '/auth/payment-status/revenuesDaily';
