/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DailyPaymentSummary } from '../../models/daily-payment-summary';

export interface GetDailyPaymentStats1$Params {
  startDate: string;
  endDate: string;
  status?: number;
}

export function getDailyPaymentStats1(http: HttpClient, rootUrl: string, params: GetDailyPaymentStats1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DailyPaymentSummary>>> {
  const rb = new RequestBuilder(rootUrl, getDailyPaymentStats1.PATH, 'get');
  if (params) {
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DailyPaymentSummary>>;
    })
  );
}

getDailyPaymentStats1.PATH = '/auth/payment-status/revenueDaily';
