/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WeeklyRevenueSummary } from '../../models/weekly-revenue-summary';

export interface GetWeeklyRevenue$Params {
  year: number;
  month: number;
}

export function getWeeklyRevenue(http: HttpClient, rootUrl: string, params: GetWeeklyRevenue$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WeeklyRevenueSummary>>> {
  const rb = new RequestBuilder(rootUrl, getWeeklyRevenue.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
    rb.query('month', params.month, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WeeklyRevenueSummary>>;
    })
  );
}

getWeeklyRevenue.PATH = '/auth/payment-status/revenueWeekly';
