/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentStatuss } from '../../models/payment-statuss';

export interface GetAllPaymentStatuses$Params {
}

export function getAllPaymentStatuses(http: HttpClient, rootUrl: string, params?: GetAllPaymentStatuses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PaymentStatuss>>> {
  const rb = new RequestBuilder(rootUrl, getAllPaymentStatuses.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PaymentStatuss>>;
    })
  );
}

getAllPaymentStatuses.PATH = '/auth/payment-status/getAllPayments';
