/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MonthlyRevenueSummary } from '../../models/monthly-revenue-summary';

export interface GetMonthlyRevenue$Params {
  year: number;
}

export function getMonthlyRevenue(http: HttpClient, rootUrl: string, params: GetMonthlyRevenue$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MonthlyRevenueSummary>>> {
  const rb = new RequestBuilder(rootUrl, getMonthlyRevenue.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MonthlyRevenueSummary>>;
    })
  );
}

getMonthlyRevenue.PATH = '/auth/payment-status/revenueMonthly';
