/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentStatuss } from '../../models/payment-statuss';

export interface GetByExternalRef$Params {
  externalRef: string;
}

export function getByExternalRef(http: HttpClient, rootUrl: string, params: GetByExternalRef$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentStatuss>> {
  const rb = new RequestBuilder(rootUrl, getByExternalRef.PATH, 'get');
  if (params) {
    rb.path('externalRef', params.externalRef, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentStatuss>;
    })
  );
}

getByExternalRef.PATH = '/auth/payment-status/external/{externalRef}';
