/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentStatusResponseDto } from '../../models/payment-status-response-dto';

export interface PaymentForFarmer$Params {
}

export function paymentForFarmer(http: HttpClient, rootUrl: string, params?: PaymentForFarmer$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PaymentStatusResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, paymentForFarmer.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PaymentStatusResponseDto>>;
    })
  );
}

paymentForFarmer.PATH = '/auth/payment-status/forFarmer';
