/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { UniversityControllerService } from './services/university-controller.service';
import { ExamCheckRecordControllerService } from './services/exam-check-record-controller.service';
import { ProgramControllerService } from './services/program-controller.service';
import { CategoryControllerService } from './services/category-controller.service';
import { BiodataControllerService } from './services/biodata-controller.service';
import { WaecControllersService } from './services/waec-controllers.service';
import { AuthenticationService } from './services/authentication.service';
import { SmsControllerService } from './services/sms-controller.service';
import { PaymentControllerService } from './services/payment-controller.service';
import { PaymentStatusControllerService } from './services/payment-status-controller.service';
import { EligibilityControllerService } from './services/eligibility-controller.service';
import { EligibilityRecordControllerService } from './services/eligibility-record-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    UniversityControllerService,
    ExamCheckRecordControllerService,
    ProgramControllerService,
    CategoryControllerService,
    BiodataControllerService,
    WaecControllersService,
    AuthenticationService,
    SmsControllerService,
    PaymentControllerService,
    PaymentStatusControllerService,
    EligibilityControllerService,
    EligibilityRecordControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
