/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AlternativeProgramDto } from './models/alternative-program-dto';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { EligibleProgramDto } from './models/eligible-program-dto';
export type { Program } from './models/program';
export type { ProgramRequestDto } from './models/program-request-dto';
export type { RegistrationRequest } from './models/registration-request';
export type { University } from './models/university';
export type { UniversityEligibilityDto } from './models/university-eligibility-dto';
export type { WaecCandidateEntity } from './models/waec-candidate-entity';
export type { WaecResultDetailEntity } from './models/waec-result-detail-entity';
export type { WaecResultsRequest } from './models/waec-results-request';
