/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AiRecommendation } from './models/ai-recommendation';
export type { AlternativeProgram } from './models/alternative-program';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { Category } from './models/category';
export type { CategoryIdDto } from './models/category-id-dto';
export type { CategoryRequest } from './models/category-request';
export type { EligibilityRecord } from './models/eligibility-record';
export type { EligibleProgram } from './models/eligible-program';
export type { ExamCheckRecord } from './models/exam-check-record';
export type { ForgottenPasswordRequest } from './models/forgotten-password-request';
export type { MoolrePaymentRequest } from './models/moolre-payment-request';
export type { MoolrePaymentResponse } from './models/moolre-payment-response';
export type { PaymentData } from './models/payment-data';
export type { PaymentStatusRequest } from './models/payment-status-request';
export type { PaymentStatuss } from './models/payment-statuss';
export type { Program } from './models/program';
export type { ProgramRequestDto } from './models/program-request-dto';
export type { ProgramWithCategoriesDto } from './models/program-with-categories-dto';
export type { RegistrationRequest } from './models/registration-request';
export type { ResetPasswordRequest } from './models/reset-password-request';
export type { SendSmsRequest } from './models/send-sms-request';
export type { University } from './models/university';
export type { UniversityEligibility } from './models/university-eligibility';
export type { WaecCandidateEntity } from './models/waec-candidate-entity';
export type { WaecResultDetailEntity } from './models/waec-result-detail-entity';
export type { WaecResultsRequest } from './models/waec-results-request';
