/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ExamCheckRecordControllerService } from './services/exam-check-record-controller.service';
export { CategoryControllerService } from './services/category-controller.service';
export { WaecControllersService } from './services/waec-controllers.service';
export { AuthenticationService } from './services/authentication.service';
export { SmsControllerService } from './services/sms-controller.service';
export { ProgramControllerService } from './services/program-controller.service';
export { PaymentControllerService } from './services/payment-controller.service';
export { EligibilityControllerService } from './services/eligibility-controller.service';
export { UniversityControllerService } from './services/university-controller.service';
export { EligibilityRecordControllerService } from './services/eligibility-record-controller.service';
