/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { WaecControllersService } from './services/waec-controllers.service';
export { AuthenticationService } from './services/authentication.service';
export { ProgramControllerService } from './services/program-controller.service';
export { EligibilityControllerService } from './services/eligibility-controller.service';
export { UniversityControllerService } from './services/university-controller.service';
