/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageUser } from '../../models/page-user';

export interface GetLatestNonAdminUsers$Params {
  count?: number;
}

export function getLatestNonAdminUsers(http: HttpClient, rootUrl: string, params?: GetLatestNonAdminUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageUser>> {
  const rb = new RequestBuilder(rootUrl, getLatestNonAdminUsers.PATH, 'get');
  if (params) {
    rb.query('count', params.count, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageUser>;
    })
  );
}

getLatestNonAdminUsers.PATH = '/auth/latest/non-admins';
