/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageUserSummaryDto } from '../../models/page-user-summary-dto';

export interface GetLatestUsersSummary$Params {
  count?: number;
}

export function getLatestUsersSummary(http: HttpClient, rootUrl: string, params?: GetLatestUsersSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<PageUserSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, getLatestUsersSummary.PATH, 'get');
  if (params) {
    rb.query('count', params.count, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageUserSummaryDto>;
    })
  );
}

getLatestUsersSummary.PATH = '/auth/latestUsersSummary';
