/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegionStatsResponse } from '../../models/region-stats-response';

export interface GetRegionStatistics$Params {
}

export function getRegionStatistics(http: HttpClient, rootUrl: string, params?: GetRegionStatistics$Params, context?: HttpContext): Observable<StrictHttpResponse<RegionStatsResponse>> {
  const rb = new RequestBuilder(rootUrl, getRegionStatistics.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RegionStatsResponse>;
    })
  );
}

getRegionStatistics.PATH = '/auth/biodata/stats';
