/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BiodataResponse } from '../../models/biodata-response';

export interface GetBiodataByRecordId$Params {
  recordId: string;
}

export function getBiodataByRecordId(http: HttpClient, rootUrl: string, params: GetBiodataByRecordId$Params, context?: HttpContext): Observable<StrictHttpResponse<BiodataResponse>> {
  const rb = new RequestBuilder(rootUrl, getBiodataByRecordId.PATH, 'get');
  if (params) {
    rb.path('recordId', params.recordId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BiodataResponse>;
    })
  );
}

getBiodataByRecordId.PATH = '/auth/biodata/byrecordId/{recordId}';
