/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Biodata } from '../../models/biodata';

export interface UpdateBiodata1$Params {
      body: Biodata
}

export function updateBiodata1(http: HttpClient, rootUrl: string, params: UpdateBiodata1$Params, context?: HttpContext): Observable<StrictHttpResponse<Biodata>> {
  const rb = new RequestBuilder(rootUrl, updateBiodata1.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Biodata>;
    })
  );
}

updateBiodata1.PATH = '/auth/biodata/updateBiodata';
