/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { University } from '../../models/university';

export interface GetUniversityById1$Params {
  id: number;
}

export function getUniversityById1(http: HttpClient, rootUrl: string, params: GetUniversityById1$Params, context?: HttpContext): Observable<StrictHttpResponse<University>> {
  const rb = new RequestBuilder(rootUrl, getUniversityById1.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<University>;
    })
  );
}

getUniversityById1.PATH = '/auth/getUniversityById/{id}';
