/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { University } from '../../models/university';
import { UpdateUniversityDto } from '../../models/update-university-dto';

export interface UpdateUniversity$Params {
      body: UpdateUniversityDto
}

export function updateUniversity(http: HttpClient, rootUrl: string, params: UpdateUniversity$Params, context?: HttpContext): Observable<StrictHttpResponse<University>> {
  const rb = new RequestBuilder(rootUrl, updateUniversity.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<University>;
    })
  );
}

updateUniversity.PATH = '/auth/updateUniverity';
