// Reference data for AllProgramsComponent.
// Subject names match those used in the validated university JSON data files.

export const CATEGORIES: { [key: string]: string[] } = {
  Science: [
    'ENGLISH LANGUAGE', 'INTEGRATED SCIENCE', 'BIOLOGY', 'CHEMISTRY',
    'PHYSICS', 'CORE MATHEMATICS', 'ELECTIVE MATHEMATICS',
  ],
  Arts: [
    'ENGLISH LANGUAGE', 'SOCIAL STUDIES', 'GOVERNMENT',
    'CORE MATHEMATICS', 'LITERATURE IN ENGLISH',
  ],
  Business: [
    'ENGLISH LANGUAGE', 'CORE MATHEMATICS', 'FINANCIAL ACCOUNTING',
    'ECONOMICS', 'BUSINESS MANAGEMENT',
  ],
};

export const COMBINED_SUBJECTS: string[] = [
  // Core
  'ENGLISH LANGUAGE',
  'CORE MATHEMATICS',
  'INTEGRATED SCIENCE',
  'SOCIAL STUDIES',

  // Science electives
  'ELECTIVE MATHEMATICS',
  'BIOLOGY',
  'CHEMISTRY',
  'PHYSICS',
  'GENERAL AGRICULTURE',
  'AGRICULTURAL SCIENCE',
  'ANIMAL HUSBANDRY',
  'CROP HUSBANDRY AND HORTICULTURE',
  'HORTICULTURE',
  'FISHERIES',
  'FORESTRY',

  // Business electives
  'FINANCIAL ACCOUNTING',
  'ACCOUNTING',
  'COST ACCOUNTING',
  'COSTING',
  'BUSINESS MANAGEMENT',
  'ECONOMICS',
  'BUSINESS MATHEMATICS',
  'FINANCE',

  // Arts / Humanities
  'LITERATURE IN ENGLISH',
  'HISTORY',
  'GEOGRAPHY',
  'GOVERNMENT',
  'CHRISTIAN RELIGIOUS STUDIES',
  'ISLAMIC RELIGIOUS STUDIES',
  'FRENCH',

  // Ghanaian languages
  'GHANAIAN LANGUAGE',
  'GHANAIAN LANGUAGES',
  'AKAN',
  'EWE',
  'GA',
  'DAGBANI',
  'NZEMA',
  'TWI',

  // Technical / Vocational
  'TECHNICAL DRAWING',
  'APPLIED ELECTRICITY',
  'ELECTRONICS',
  'AUTO MECHANICS',
  'BUILDING CONSTRUCTION',
  'METALWORK',
  'METAL WORK',
  'WOODWORK',
  'ENGINEERING SCIENCE',

  // Home Economics
  'FOOD AND NUTRITION',
  'MANAGEMENT IN LIVING',
  'CLOTHING AND TEXTILES',

  // Visual Arts
  'GENERAL KNOWLEDGE IN ART',
  'GRAPHIC DESIGN',
  'PICTURE MAKING',
  'SCULPTURE',
  'CERAMICS',
  'TEXTILES',
  'LEATHERWORK',
  'JEWELLERY',
  'BASKETRY',

  // Other
  'MUSIC',
  'PHYSICAL EDUCATION',
  'FURTHER MATHEMATICS',
  'INFORMATION AND COMMUNICATION TECHNOLOGY',
  'INFORMATION AND COMMUNICATION TECHNOLOGY (ICT)',
];
