/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UniversityEligibilityDto } from '../../models/university-eligibility-dto';
import { WaecCandidateEntity } from '../../models/waec-candidate-entity';

export interface CheckEligibility$Params {
      body: WaecCandidateEntity
}

export function checkEligibility(http: HttpClient, rootUrl: string, params: CheckEligibility$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UniversityEligibilityDto>>> {
  const rb = new RequestBuilder(rootUrl, checkEligibility.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UniversityEligibilityDto>>;
    })
  );
}

checkEligibility.PATH = '/auth/check-eligibilityAll';
