/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExamCheckMonthlySummary } from '../../models/exam-check-monthly-summary';

export interface GetMonthlyStats$Params {
  year: number;
}

export function getMonthlyStats(http: HttpClient, rootUrl: string, params: GetMonthlyStats$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExamCheckMonthlySummary>>> {
  const rb = new RequestBuilder(rootUrl, getMonthlyStats.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ExamCheckMonthlySummary>>;
    })
  );
}

getMonthlyStats.PATH = '/auth/records/monthlyStats';
