/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExamRecordStatsDto } from '../../models/exam-record-stats-dto';

export interface GetFilteredStats$Params {
  startDate?: string;
  endDate?: string;
}

export function getFilteredStats(http: HttpClient, rootUrl: string, params?: GetFilteredStats$Params, context?: HttpContext): Observable<StrictHttpResponse<ExamRecordStatsDto>> {
  const rb = new RequestBuilder(rootUrl, getFilteredStats.PATH, 'get');
  if (params) {
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExamRecordStatsDto>;
    })
  );
}

getFilteredStats.PATH = '/auth/records/stats/filtered';
