/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExamCheckRecord } from '../../models/exam-check-record';

export interface UpdatePaymentStatus$Params {
  id: string;
      body: {
[key: string]: string;
}
}

export function updatePaymentStatus(http: HttpClient, rootUrl: string, params: UpdatePaymentStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<ExamCheckRecord>> {
  const rb = new RequestBuilder(rootUrl, updatePaymentStatus.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExamCheckRecord>;
    })
  );
}

updatePaymentStatus.PATH = '/auth/records/{id}/paymentStatus';
