import { Component, Input } from '@angular/core';
import { ManaulServiceService } from 'src/app/Utilities/manaul-service.service';
import { EligibilityResult } from 'src/app/customModels/eligibility.model';
import { MatSnackBar } from '@angular/material/snack-bar';

// Types used by the HTML template
type SectionKey = 'core' | 'alternative' | 'recommendations';
type SectionElegibleKey = 'core' | 'eligibility' | 'recommendations';

interface ParsedLine {
  status: 'pass' | 'fail' | 'excellent' | 'neutral';
  subject: string;
  requirement?: string;
  yourGrade?: string;
  remarks: string;
  originalLine: string;
}

interface RecommendationSections {
  core: ParsedLine[];
  alternative: ParsedLine[];
  recommendations: string[];
}

@Component({
  selector: 'app-user-eligibility',
  templateUrl: './user-eligibility.component.html',
  styleUrls: ['./user-eligibility.component.css']
})
export class UserEligibilityComponent {

  @Input() records: EligibilityResult[] = [];

  expandedResultId: string | null = null;
  selectedResult: EligibilityResult | null = null;
  showModal = false;
  isLoading = false;
  loadingError = false;

  activeCardId: number | null = null;
  showAll: Record<string, Record<SectionKey, boolean>> = {};
  showAllElegiblity: Record<string, Record<SectionElegibleKey, boolean>> = {};

  // Section markers for recommendation text parsing
  SECTION_MARKERS = {
    CORE_HEADER: '[CORE_SUBJECTS]',
    ALTERNATIVE_HEADER: '[ALTERNATIVE_REQUIREMENTS]',
    RECOMMENDATIONS_HEADER: '[RECOMMENDATIONS]',
    PASS: '[PASS]',
    FAIL: '[FAIL]',
    INFO: '[INFO]',
    EXCELLENT: '[EXCELLENT]'
  };

  constructor(
    private manualService: ManaulServiceService,
    private snackBar: MatSnackBar
  ) {}

  ngOnInit(): void {
    this.recordByUser();
  }

  // ── Data loading ────────────────────────────────────────────────────────────

  recordByUser(): void {
    this.isLoading = true;
    this.loadingError = false;
    this.manualService.eligibilityRecordsByUser().subscribe({
      next: (data: any) => {
        this.records = (data as any[]).sort((a, b) =>
          new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
        );
        this.isLoading = false;
      },
      error: (err) => {
        this.loadingError = true;
        this.isLoading = false;
        this.snackBar.open('Failed to load results', 'Dismiss', {
          duration: 5000,
          panelClass: ['error-snackbar']
        });
        console.error('Fetching Records error:', err);
      }
    });
  }

  // ── UI interactions ─────────────────────────────────────────────────────────

  toggleExpand(resultId: string): void {
    this.expandedResultId = this.expandedResultId === resultId ? null : resultId;
  }

  openPreview(result: EligibilityResult): void {
    this.selectedResult = result;
    this.showModal = true;
  }

  closeModal(): void {
    this.showModal = false;
  }

  toggleCard(event: Event): void {
    const card = (event.target as HTMLElement).closest('.eligibility-card');
    card?.classList.toggle('active');
  }

  isCardActive(programId: number): boolean {
    return this.activeCardId === programId;
  }

  toggleShowAll(programId: string, section: SectionKey): void {
    if (!this.showAll[programId]) {
      this.showAll[programId] = { core: false, alternative: false, recommendations: false };
    }
    this.showAll[programId][section] = !this.showAll[programId][section];
  }

  toggleShowAllEligible(programId: string, section: SectionElegibleKey): void {
    if (!this.showAllElegiblity[programId]) {
      this.showAllElegiblity[programId] = { core: false, eligibility: false, recommendations: false };
    }
    this.showAllElegiblity[programId][section] = !this.showAllElegiblity[programId][section];
  }

  isShowingAll(programId: string, section: SectionKey): boolean {
    return this.showAll[programId]?.[section] ?? false;
  }

  // ── Download ────────────────────────────────────────────────────────────────

  /**
   * Downloads the eligibility report as a PDF generated by the backend.
   */
  downloadAsPdf(result: EligibilityResult): void {
    this.isLoading = true;
    this.manualService.downloadEligibilityReport(result.id).subscribe({
      next: (blob: Blob) => {
        this.isLoading = false;
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        const safeName = result.examCheckRecord?.candidateName?.replace(/\s+/g, '_') || 'Candidate';
        link.download = `Eligibility_Assessment_${safeName}_${Date.now()}.pdf`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
      },
      error: (err) => {
        this.isLoading = false;
        this.snackBar.open('Failed to generate report. Please try again.', 'Dismiss', {
          duration: 5000,
          panelClass: ['error-snackbar']
        });
        console.error('PDF generation failed:', err);
      }
    });
  }

  downloadAsJson(result: EligibilityResult): void {
    const dataStr = JSON.stringify(result, null, 2);
    const dataUri = 'data:application/json;charset=utf-8,' + encodeURIComponent(dataStr);
    this.triggerDownload(dataUri, `${result.id}.json`);
  }

  private triggerDownload(dataUri: string, fileName: string): void {
    const link = document.createElement('a');
    link.setAttribute('href', dataUri);
    link.setAttribute('download', fileName);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  // ── Template helpers ────────────────────────────────────────────────────────

  getSubjects(cutoffPoints: { [subject: string]: string }): string[] {
    return Object.keys(cutoffPoints);
  }

  getUniversityTypes(result: EligibilityResult): string[] {
    const types = new Set<string>();
    result.universities.forEach(uni => types.add(uni.type));
    return Array.from(types);
  }

  hasProgramsInCategory(programs: any[], category: string): boolean {
    if (!programs || !category) return false;
    return programs.some(program => program.categories?.includes(category));
  }

  getProgramsByCategory(programs: any[], category: string): any[] {
    if (!programs || !category) return [];
    return programs.filter(program => program.categories?.includes(category));
  }

  getTotalEligiblePrograms(result: EligibilityResult): number {
    return result.universities.reduce((total, uni) =>
      total + (uni.eligiblePrograms?.length ?? 0), 0);
  }

  getTotalAlternativePrograms(result: EligibilityResult): number {
    return result.universities.reduce((total, uni) =>
      total + (uni.alternativePrograms?.length ?? 0), 0);
  }

  getVisibleItems(
    sections: RecommendationSections,
    section: 'core' | 'alternative',
    programId: string,
    limit: number = 3
  ): ParsedLine[] {
    const items = sections[section] || [];
    return this.isShowingAll(programId, section) ? items : items.slice(0, limit);
  }

  getVisibleRecommendations(
    sections: RecommendationSections,
    programId: string,
    limit: number = 3
  ): string[] {
    const items = sections.recommendations || [];
    return this.isShowingAll(programId, 'recommendations') ? items : items.slice(0, limit);
  }

  hasMoreItems(
    sections: RecommendationSections,
    section: SectionKey,
    limit: number = 3
  ): boolean {
    if (section === 'recommendations') return sections.recommendations.length > limit;
    return sections[section].length > limit;
  }

  getStatusIcon(parsedLine: ParsedLine): string {
    switch (parsedLine.status) {
      case 'excellent': return '✅';
      case 'pass':      return '✅';
      case 'fail':      return '❌';
      default:          return 'ℹ️';
    }
  }

  getRecommendationIcon(recommendation: string): string {
    if (recommendation.toLowerCase().includes('missing')) return '📋';
    if (recommendation.toLowerCase().includes('strong') ||
        recommendation.toLowerCase().includes('performance')) return '⭐';
    return '💡';
  }

  getStatusClass(status: string): string {
    return `status-${status}`;
  }

  // ── Recommendation text parsing ─────────────────────────────────────────────

  parseRecommendation(text: string): RecommendationSections {
    if (!text) return { core: [], alternative: [], recommendations: [] };

    const lines = text.split('\n').map(l => l.trim()).filter(l => l.length > 0);
    const sections: RecommendationSections = { core: [], alternative: [], recommendations: [] };
    let currentSection: SectionKey | null = null;

    for (const line of lines) {
      if (this.isCoreSection(line))            { currentSection = 'core';            continue; }
      if (this.isAlternativeSection(line))     { currentSection = 'alternative';     continue; }
      if (this.isRecommendationsSection(line)) { currentSection = 'recommendations'; continue; }
      if (this.isHeaderLine(line))             { continue; }

      if (currentSection === 'core' || currentSection === 'alternative') {
        const parsed = this.parseLine(line);
        if (parsed) sections[currentSection].push(parsed);
      } else if (currentSection === 'recommendations') {
        const cleanLine = this.cleanRecommendationLine(line);
        if (cleanLine) sections.recommendations.push(cleanLine);
      }
    }

    return sections;
  }

  private isCoreSection(line: string): boolean {
    return line.includes(this.SECTION_MARKERS.CORE_HEADER) ||
           line.includes('CORE SUBJECTS ANALYSIS') ||
           line.includes('CORE SUBJECTS') ||
           /^[??🎯📚]\s*CORE/i.test(line);
  }

  private isAlternativeSection(line: string): boolean {
    return line.includes(this.SECTION_MARKERS.ALTERNATIVE_HEADER) ||
           line.includes('ALTERNATIVE REQUIREMENTS') ||
           /^[??🔄]\s*ALTERNATIVE REQUIREMENTS/i.test(line);
  }

  private isRecommendationsSection(line: string): boolean {
    return line.includes(this.SECTION_MARKERS.RECOMMENDATIONS_HEADER) ||
           line.includes('RECOMMENDATIONS:') ||
           /^[??💡]\s*RECOMMENDATIONS/i.test(line);
  }

  private isHeaderLine(line: string): boolean {
    if (line.startsWith('[') && line.includes(']') && !line.includes(':')) return true;
    if (/^[??⚠️📚🔄💡🎯⭐📋]\s*[A-Z\s]+:?\s*$/.test(line))            return true;
    if (/^[??⚠️]\s*(ELIGIBLE|ALTERNATIVE|NOT ELIGIBLE)/i.test(line))    return true;
    return false;
  }

  private cleanRecommendationLine(line: string): string {
    return line
      .replace(/^\?\?\s*/, '')
      .replace(/^\[(?:PASS|FAIL|INFO|EXCELLENT)\]\s*/, '')
      .replace(/^[📋⭐💡]\s*/, '')
      .trim();
  }

  private parseLine(line: string): ParsedLine | null {
    const cleanLine = line
      .replace(/^\?\?\s*/, '')
      .replace(/^\?\s*/, '')
      .replace(/^\[(?:PASS|FAIL|INFO|EXCELLENT)\]\s*/, '')
      .replace(/^[✅❌ℹ️]\s*/, '')
      .trim();

    if (!cleanLine) return null;

    const status = this.getLineStatus(line);

    const gradePattern = /^([^:]+):\s*([A-D]\d+)\s*\(Required:\s*([A-D]\d+)\)\s*-\s*(.+)$/;
    const gradeMatch = cleanLine.match(gradePattern);
    if (gradeMatch) {
      return { status, subject: gradeMatch[1].trim(), yourGrade: gradeMatch[2].trim(),
               requirement: gradeMatch[3].trim(), remarks: gradeMatch[4].trim(), originalLine: line };
    }

    const missingPattern = /^([^:]+):\s*Missing\s*\(Required:\s*([A-D]\d+)\)$/;
    const missingMatch = cleanLine.match(missingPattern);
    if (missingMatch) {
      return { status: 'fail', subject: missingMatch[1].trim(),
               requirement: missingMatch[2].trim(), remarks: 'Missing', originalLine: line };
    }

    const groupPattern = /No matching subjects found in group:\s*\[([^\]]+)\]/;
    const groupMatch = cleanLine.match(groupPattern);
    if (groupMatch) {
      return { status: 'fail', subject: 'Group Requirement',
               remarks: `No match in: ${groupMatch[1].trim()}`, originalLine: line };
    }

    // Elective / group summary lines — user-friendly text
    if (cleanLine.includes('Elective requirement satisfied') ||
        cleanLine.includes('All required elective subjects passed')) {
      return { status: 'pass', subject: cleanLine, remarks: '', originalLine: line };
    }
    if (cleanLine.includes('Elective requirement not met') ||
        cleanLine.includes('Not all required elective subjects passed') ||
        cleanLine.includes('None of the subjects in this group qualify')) {
      return { status: 'fail', subject: cleanLine, remarks: '', originalLine: line };
    }
    // Legacy fallback for older records still containing allOf/anyOf text
    if (cleanLine.includes('Alternative') && cleanLine.includes('requirement met')) {
      return { status: 'pass', subject: 'Elective requirement satisfied', remarks: '', originalLine: line };
    }
    if (cleanLine.includes('Alternative') && (cleanLine.includes('not met') || cleanLine.includes('anyOf'))) {
      return { status: 'fail', subject: 'Elective requirement not met', remarks: '', originalLine: line };
    }

    return { status, subject: cleanLine, remarks: '', originalLine: line };
  }

  private getLineStatus(line: string): 'pass' | 'fail' | 'excellent' | 'neutral' {
    if (line.includes('[EXCELLENT]') || (line.includes('[PASS]') && line.includes('Excellent!'))) return 'excellent';
    if (line.includes('[PASS]')) return 'pass';
    if (line.includes('[FAIL]')) return 'fail';

    const cleanLine = line.replace(/^\?\?\s*/, '');
    if (cleanLine.includes('Excellent!') || cleanLine.includes('requirement met')) return 'excellent';
    if (cleanLine.includes('Missing') || cleanLine.includes('Does not meet') ||
        cleanLine.includes('No matching subjects found')) return 'fail';

    const match = cleanLine.match(/([A-D]\d+)\s*\(Required:\s*([A-D]\d+)\)/);
    if (match) {
      return this.compareGrades(match[1], match[2]) >= 0
        ? (cleanLine.includes('Excellent!') ? 'excellent' : 'pass')
        : 'fail';
    }

    return 'neutral';
  }

  private compareGrades(grade1: string, grade2: string): number {
    const gradeValues: Record<string, number> = {
      'A1': 1, 'B2': 2, 'B3': 3, 'C4': 4, 'C5': 5, 'C6': 6, 'D7': 7, 'E8': 8, 'F9': 9
    };
    return (gradeValues[grade2] || 99) - (gradeValues[grade1] || 99);
  }

  // ── Elective / Alternative Requirements — 3-column layout helpers ──────────

  groupAltItems(items: ParsedLine[]): { met: ParsedLine[], missing: ParsedLine[], below: ParsedLine[] } {
    return {
      met:     items.filter(i => i.status === 'pass' || i.status === 'excellent'),
      missing: items.filter(i => i.status === 'fail' && (!i.yourGrade || i.remarks === 'Missing')),
      below:   items.filter(i => i.status === 'fail' && !!i.yourGrade && i.remarks !== 'Missing')
    };
  }

  altRowIndices(groups: { met: ParsedLine[], missing: ParsedLine[], below: ParsedLine[] }): number[] {
    const len = Math.max(groups.met.length, groups.missing.length, groups.below.length);
    return Array.from({ length: len }, (_, i) => i);
  }

  formatAltCell(item: ParsedLine | undefined): string {
    if (!item) return '';
    let text = item.subject;
    if (item.yourGrade && item.requirement) {
      text += ` — ${item.yourGrade} (Req. ${item.requirement})`;
    } else if (item.requirement) {
      text += ` (Req. ${item.requirement})`;
    }
    return text;
  }
}
