/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { checkEligibility } from '../fn/eligibility-controller/check-eligibility';
import { CheckEligibility$Params } from '../fn/eligibility-controller/check-eligibility';
import { EligibilityRecord } from '../models/eligibility-record';

@Injectable({ providedIn: 'root' })
export class EligibilityControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `checkEligibility()` */
  static readonly CheckEligibilityPath = '/auth/check-eligibility';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkEligibility()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  checkEligibility$Response(params: CheckEligibility$Params, context?: HttpContext): Observable<StrictHttpResponse<EligibilityRecord>> {
    return checkEligibility(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkEligibility$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  checkEligibility(params: CheckEligibility$Params, context?: HttpContext): Observable<EligibilityRecord> {
    return this.checkEligibility$Response(params, context).pipe(
      map((r: StrictHttpResponse<EligibilityRecord>): EligibilityRecord => r.body)
    );
  }

}
