/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addProgramToUniversity } from '../fn/program-controller/add-program-to-university';
import { AddProgramToUniversity$Params } from '../fn/program-controller/add-program-to-university';
import { getProgramsByUniversity } from '../fn/program-controller/get-programs-by-university';
import { GetProgramsByUniversity$Params } from '../fn/program-controller/get-programs-by-university';
import { Program } from '../models/program';

@Injectable({ providedIn: 'root' })
export class ProgramControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `addProgramToUniversity()` */
  static readonly AddProgramToUniversityPath = '/auth/programs/addProgram';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addProgramToUniversity()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addProgramToUniversity$Response(params: AddProgramToUniversity$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Program>>> {
    return addProgramToUniversity(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addProgramToUniversity$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addProgramToUniversity(params: AddProgramToUniversity$Params, context?: HttpContext): Observable<Array<Program>> {
    return this.addProgramToUniversity$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Program>>): Array<Program> => r.body)
    );
  }

  /** Path part for operation `getProgramsByUniversity()` */
  static readonly GetProgramsByUniversityPath = '/auth/programs/university/{universityId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProgramsByUniversity()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProgramsByUniversity$Response(params: GetProgramsByUniversity$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Program>>> {
    return getProgramsByUniversity(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProgramsByUniversity$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProgramsByUniversity(params: GetProgramsByUniversity$Params, context?: HttpContext): Observable<Array<Program>> {
    return this.getProgramsByUniversity$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Program>>): Array<Program> => r.body)
    );
  }

}
