/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { sendSms } from '../fn/sms-controller/send-sms';
import { SendSms$Params } from '../fn/sms-controller/send-sms';

@Injectable({ providedIn: 'root' })
export class SmsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `sendSms()` */
  static readonly SendSmsPath = '/auth/sms/send';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendSms()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendSms$Response(params: SendSms$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return sendSms(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendSms$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendSms(params: SendSms$Params, context?: HttpContext): Observable<string> {
    return this.sendSms$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
