/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Program } from '../../models/program';

export interface GetProgramsByCategoryName$Params {
  categoryName: string;
}

export function getProgramsByCategoryName(http: HttpClient, rootUrl: string, params: GetProgramsByCategoryName$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Program>>> {
  const rb = new RequestBuilder(rootUrl, getProgramsByCategoryName.PATH, 'get');
  if (params) {
    rb.path('categoryName', params.categoryName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Program>>;
    })
  );
}

getProgramsByCategoryName.PATH = '/auth/programs/by-category-name/{categoryName}';
